### ISSUE TITLE
Add ClusterResourceQuota CRD's

### ISSUE THREAD

**Issue by moshloop** [flanksource/platform-operator#1]
To mirror/replicate: https://docs.openshift.com/container-platform/3.3/admin_guide/multiproject_quota.html

**Comment by mazzy89** [comment]
At the current stage, Vanilla kubernetes does not support `ClusterResourceQuota` resource but only `ResourceQuota` that apply to a single namespace.

What we would like to do here is to implement from scratch the same behavior of `ClusterResourceQuota` that Openshit already has. 

This would require to build a Custom Admission Controller.

** Design **

Create a `ValidatingWebhookConfiguration` resource that defines the endpoint of the custom validating webhook controller that will be executed each time a new resource is created into the cluster.

The custom validating controller would implement a logic that checks per request if the defined quotas are respected and reply in a binary way according to the current status of the entire cluster.

Since `ClusterResourceQuota` CRD does not exist, we would need to create it and register to the API server.

cc @moshloop

**Comment by mazzy89** [comment]
@moshloop The idea here how to proceed in practice is to create first the CRD via [kubebuilder](https://github.com/kubernetes-sigs/kubebuilder). This would require little stress and would be pretty fast. 

Next, I would like to get migrate the project to kubebuilder. Considering the status of the project this would not require much time. At this stage, only one controller would need to be migrated and the logic is pretty simple and straightforward. Once done that, we would add the logic for the admission plugin that handles `ClusterResourceQuota`. 

---------

In the case of `ClusterResourceQuota` on Openshift, it uses selector and/or annotations to apply the quotas to a specific _projects_ (groups of resources in Openshift). See here https://github.com/openshift/openshift-apiserver/blob/master/pkg/quota/apis/quota/types.go - we would not use that. am I right @moshloop?

`ResourceQuota` makes available to be consumed externally this handy function https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/resourcequota/controller.go#L401 Need to check if it is possible to be used in our case in **our** admission controller.

**Comment by mazzy89** [comment]
Introduced now kubebuilder, CRD will be pretty straightforward created.

**Comment by mazzy89** [comment]
Closing this. We have been merged this week the CRD PR
